"""Add footer caption column

Revision ID: 25b1ca733ba8
Revises: 277cf75d0e2b
Create Date: 2026-04-16 22:21:29.207165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b1ca733ba8'
down_revision = '277cf75d0e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('footer_caption', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_content', schema=None) as batch_op:
        batch_op.drop_column('footer_caption')

    # ### end Alembic commands ###
