"""add location and service times to about

Revision ID: 277cf75d0e2b
Revises: 
Create Date: 2026-04-14 18:57:24.281456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277cf75d0e2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('service_times', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_content', schema=None) as batch_op:
        batch_op.drop_column('service_times')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
