"""Added text config fields

Revision ID: 30113914c0b5
Revises: 25b1ca733ba8
Create Date: 2026-04-17 05:59:45.543030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30113914c0b5'
down_revision = '25b1ca733ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('church_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('hero_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('hero_subtitle', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_content', schema=None) as batch_op:
        batch_op.drop_column('meta_description')
        batch_op.drop_column('hero_subtitle')
        batch_op.drop_column('hero_title')
        batch_op.drop_column('church_name')

    # ### end Alembic commands ###
